### ISSUE TITLE
entitlement analyzer does not load historical data

### ISSUE THREAD

**Issue by spgpstrategy** [qlik-oss/qlik-cloud-entitlement-analyzer#13]
Team, 
I ask for your help since since 15 November we have seen failures in theMonitoring Apps (entitlement analyzer, reload analizer and app analyzer) application since it does not load historical data, we have reinstalled the application, we updated it to the latest version, we also created a new API key, but it still does not work. show historical information, it only shows the information for the days we have had in the month of December and we need to see the information for the month of November 2023, we appreciate your collaboration by telling us what we should configure or what we can do to solve it.

Thank you very much, we appreciate your prompt attention.

**Comment by calle21-21** [comment]
Having the same issue, do you have any updates? Right now I'm only receiving 2024 data.

**Comment by piotrbratek** [comment]
Same thing - couple of guys reported the issue on community - is there a way to change the timeframe in the script ?

**Comment by calle21-21** [comment]
> Same thing - couple of guys reported the issue on community - is there a way to change the timeframe in the script ?

Hey, sorry for not updating. Completely forgot about this comment. Do you by chance have older versions of the app? If so you need to connect the new versions of the monitor apps to the old qvds, I would recommend doing this by creating a separate app loading the old and new qvds, concatenating them and then storing into a new qvd with new file version. Then open the monitor app and update the vAppVersion variable to match the version specified on the the Qvd thats is being created in the separate app. If you want further details please contact me at calle.sahlin@stretch.dk and Ill help you set it up :)

**Comment by danielpilla** [comment]
Hi all. Closing this as this behavior is working as designed. As @QlikMertzi shared above, there are reasons that the application functions this way, and changes are not planned.
