### ISSUE TITLE
Track object exports

### ISSUE THREAD

**Issue by jurajmisina** [qlik-oss/qlik-cloud-entitlement-analyzer#14]
We'd like to be able to track object exports in a similar fashion as previously on-prem in Sessions monitor. This can help us to identify users who need extra enablement or support.

**Comment by withdave** [comment]
Hmm, the events are available via the audits API, so this is possible to see on a per-app level, but not directly on a per-user level using `com.qlik.v1.reporting-service.audit`. You can sort-of infer the user too if you look for the last app open event for that app via reporting service, but this isn't an exact science.

I've raised an improvement to see if we can add the userId to the event, as well as the objectId, which would give us most of what we need. I don't have a timeline for adding this information yet.

**Comment by withdave** [comment]
We are currently exploring the creation of a new monitoring app which would bring in usage across various services, and will add this as a requirement to that app. If you have any views you've created which you find particularly useful, please feel free to share them and we'll see what we can include!

Closing this ticket as we'll add this to a different app.
