### ISSUE TITLE
Loading historiccal data after upgrading to 2.3.0

### ISSUE THREAD

**Issue by serjko-brightly** [qlik-oss/qlik-cloud-entitlement-analyzer#19]
I am running into an issue when trying to link my historical data to the output of the latest app. With userId deprecated in Assignments and replaced with subject in most places, what is the best way to connect the actual data with my historical tables populated by earlier versions of the app?

To give you an example, I want to load last X months of data stored in QVDs and show it in the latest app so we can still see the usage trends. Replacing userId with subject seems concerning as the same users would now have a different ID compared to their historical records. Would appreciate your help connecting the dots between historal and actual data in the app.

**Comment by danielpilla** [comment]
Hi @serjko-brightly,
Loading historical data from the QVDs of older versions of the app is not supported for a couple of reasons, one of which you've found with this issue. If the data model/field definitions change, there is not a reliable way to merge them with the historical data. I would suggest keeping the old version of the app around as an archival app, and then continuing to reload the new app which will build incrementally over time. I realize that this is not ideal, but this is however the case and working as intended.

**Comment by serjko-brightly** [comment]
@danielpilla - Thanks for the quick response! Appreciate your advice to keep older versions for historical track records. The ability to monitor usage over time is one of the most important features for us. Hoping there won't be many instances where going from one version to another assumes losing access to the existing history. We found a way to load past QVDs as long as the schema is consistent.

Thank you for all the great work on these apps. One of our most anticipated features is tracking usage at the sheet level. Hope to see it added soon.

**Comment by danielpilla** [comment]
Hi @serjko-brightly,
Yes, we’ve thought about adding an additional flag to denote whether there has been a schema change and to conditionally build new QVDs, else Concat onto the old. If we made this change, we’d need to apply it across all of the monitoring applications however for consistency, and only this application is really impacted by this issue. I will keep it under consideration but it’s unlikely to be implemented as it’s a lot less risky to just re-roll new QVDs.

As far as sheet usage, the good news is that is currently under development! I am unsure if it will end up in the entitlement analyzer, as it’s also useful for Capacity-based tenants and we need a solution there, too. That is currently under discussion (where it will land).

Thanks for the kind words, and cheers!
