### ISSUE TITLE
Allow use of Entitlement Analyzer app for capacity licence in Qlik Cloud

### ISSUE THREAD

**Issue by CarlFortey** [qlik-oss/qlik-cloud-entitlement-analyzer#20]
Hi,
We have installed the new Entitlement Analyzer v2.3.0 and set up and configured it.
We are on capacity licencing.

Post reload in summary it shows:
*******************************
WARNING! This tenant is on a capacity-based license, which the Entitlement Analyzer does not support as it analyzes user-based licenses. Dropping all tables and halting...
*******************************

Nowhere mentions this in the guidance or troubleshooting. <<< needs updating.

Regardless of the capacity licences being different, this app still provides some useful user and app use data for us.

Please can the guidance/troubleshooting be updated, and also the app script be reviewed to allow to be used in a capacity licencing tenant?

Regards, Carl.

**Comment by danielpilla** [comment]
Hi @CarlFortey,
Thank you for the feedback. Unfortunately, the Entitlement Analyzer does not support capacity-based licenses, and there are no plans to adapt that app to multiple license types. Instead, there will likely be a usage analysis app that will not be license specific that will bridge both types. This is under consideration.

In addition, your feedback about it not being documented clearly is valid. It is however mentioned on the main page [here](https://github.com/qlik-oss/qlik-cloud-monitoring-apps?tab=readme-ov-file#qlik-cloud-monitoring-apps). I will modify the app repositories to individually reflect what license types they support.

Cheers.
