### ISSUE TITLE
Analyzer Capacity - Events duration vs Minutes used

### ISSUE THREAD

**Issue by rzenere-avvale** [qlik-oss/qlik-cloud-entitlement-analyzer#24]
## 🐛 Bug report

I'm trying to monitor users that use the Analyzer Capacity, and came across a difference between what is exposed between Events duration (which is calculated on _durationMinutes_) and Minutes used (which is calculated on _minutesUsed_).
After digging up a bit, I saw that the _/api/v1/licenses/consumption_ endpoint (which is used by the Entitlement Analyzer) exposes directly this strange data.
Below an example for _licenseUsage = TIME_LICENSE_, where _minutesUsed_ isn't always aligned with the _durationMinutes_

![image](https://github.com/qlik-oss/qlik-cloud-entitlement-analyzer/assets/103733440/f4d1b634-1cc0-4784-ab5a-32e810f813a8)

In the highlighted cells, I would expect a value <= of the _minutesUsed_ (like the not highlighted cells).

For _licenseUsage = ASSIGNED_LICENSE_, _minutesUsed_ is always 0, so _durationMinutes_ is the only way for me to say how much lasted a session.
Am I reading those columns right in this situation? Or am I missing anything? (i.e. durationMinutes tracks also the time outside of an app?)

### Steps to Reproduce

1. Configure the Entitlement Analyzer in an environment where the Analyzer Capacity 'license' is used
2. Check the data that is extracted by the Entitlement Analyzer; the check could be made:
2.1. directly on the extracted qvd, or also 
2.2 on the Entitlement Analyzer app, checking the objects 'consumption listings'  (sheet 'Users') and 'Capacity usage over time' (sheet 'Capacity usage over time')

### Expected behavior

For users that are using Analyzer Capacity, _minutesUsed_ should always be greater or equal to _durationMinutes_

### Actual behavior

_minutesUsed_ is lesser or equal to _durationMinutes_

### Additional context

1. We noticed the issue with Entitlement Analyzer 2.2.1, but the same happens also on 2.3.0
2. From my interpretation, _minutesUsed_ is the same value exposed on the Management Console and so, should be a multiple of the minimum 'block' of minutes that is used, while _durationMinutes_ should be the actual session duration/time spent analyzing an application

**Comment by danielpilla** [comment]
Hi @rzenere-avvale,
Minutes used is the amount of Analyzer Capacity packs utilized over the duration of the session. Capacity packs are triggered by app open and engine interaction. So if a user opens an app while utilizing Analyzer Capacity, they will automatically consume 6 minutes. However, if they then just keep their browser open and don't make any selections, the duration could be ~20 minutes but they would have only consumed 6 minutes worth of analyzer capacity. Please review this page which explains this in detail and provides many examples: [https://help.qlik.com/en-US/cloud-services/Subsystems/Hub/Content/Sense_Hub/Introduction/analyzer-capacity-consumption.htm](https://help.qlik.com/en-US/cloud-services/Subsystems/Hub/Content/Sense_Hub/Introduction/analyzer-capacity-consumption.htm). Closing this as WAD.

Cheers,

**Comment by rzenere-avvale** [comment]
Thanks for the clarification @danielpilla! I did not expect such a difference

Riccardo
