### ISSUE TITLE
The historical usage stats are changing after deleting users 

### ISSUE THREAD

**Issue by serjko-brightly** [qlik-oss/qlik-cloud-entitlement-analyzer#27]
We noticed that after deleting a user from a tenant, their usage stats seem to disappear from the app. This is impacting both recent usage and historical periods. Our expected behavior was that the historical usage should be retained in QVDs so that it is not impacted if any users are removed from the tenant, which will make them unavailable via API at the latest reload.

We have a weekly workflow that frees up licenses and deletes users based on certain period of inactivity. This is working as expected but also altering our historical usage stats showing in the app. I wonder if there is any option to retain the historical usage in the app after removing users from the tenant.

**Comment by withdave** [comment]
@serjko-brightly closing this as we missed it before and this is likely stale. Please feel free to reply with any updates if this is still an issue and we can look at it.
