### ISSUE TITLE
Update Entitlement Analyzer app with the last 12 months of usage consumption stats

### ISSUE THREAD

**Issue by DigitallyMeasured** [qlik-oss/qlik-cloud-entitlement-analyzer#4]
## 🚀 Feature

At my employer, we just started using the Entitlement Analyzer app and noticed the usage consumption records are filtered to the current month only. For audit purposes, we'd really like to be able to track the last 12 months.

As a Qlik admin and developer, I made an attempt to update the code to no avail.

Would it be possible to have this enhancement available?

**Comment by QlikMertzi** [comment]
@DigitallyMeasured you can find your answer over here:
https://community.qlik.com/t5/Support-Updates/Entitlement-Analyzer-for-Qlik-Sense-Enterprise-SaaS/bc-p/1852969/highlight/true#M1945

**Comment by withdave** [comment]
Tagging this with 'won't fix' as per @QlikMertzi's comment, the APIs limit us on how much quota information we can retrieve - there is not currently a reliable way of retrieving the right amount of history from both endpoints.

**Comment by DigitallyMeasured** [comment]
Thanks!

**Comment by withdave** [comment]
Closing per comments above.
